RM = /bin/rm -f
CC = g++ 
CFLAGS = -std=c++11 -Wall -pedantic -D_DEBUG -g

snake.out :
	 $(CC) $(CFLAGS) main.cpp -lGL -lGLU -lglut  -o snake 

.PHONY : clean
clean :
	$(RM) *.out 

.PHONY: all
all: snake.out
